[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88
skip = [
    "env",
    ".git",
    "__pycache__",
    "build",
    "dist"
]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
per-file-ignores = {"__init__.py" = ["F401"]}
exclude = [
    "env",
    ".git",
    "__pycache__",
    "build",
    "dist"
]

[tool.mypy]
python_version = "3.11"
mypy_path = "."
ignore_missing_imports = true
follow_imports = "skip"
exclude = '(env/|__pycache__/|build/|dist/|.git/)'
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
