name: Agent Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'agent/**'
      - '.github/workflows/agent-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'agent/**'
      - '.github/workflows/agent-ci.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agent
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            agent/requirements.txt
            agent/requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Black formatting check
        run: black --check .

      - name: isort import order check
        run: isort --check-only .

      - name: flake8 linting
        run: flake8 .

      - name: mypy type checking
        run: mypy .

      - name: pytest
        run: pytest --maxfail=1 --disable-warnings -q
